### ISSUE TITLE
401 Error when trying to join into a space

### ISSUE THREAD

**Issue by barahonajm** [vsls-contrib/spaces#104]
Hi, thank you for this awesome extension!

I just want to report an issues I found when trying to connect into an space: 

![image](https://user-images.githubusercontent.com/15148088/67221396-5fbae180-f3f9-11e9-92d9-b46df68e4050.png)

Could you please help me?

**Comment by lostintangent** [comment]
@barahonajm Can you try running the `Developer: Reload Window` command and see if that unblocks you? It seems like we have a bug where the auth token expires (or something), and so we need to fix that. However, if you try reloading VS Code, that might be a temporary workaround. Thanks!

**Comment by barahonajm** [comment]
Thank you very muy for your response: 

I have executed   `> Developer: Reload Window` command as well as to re-open vscode a couple of times but I am still getting the exact same issue.

But if this will be fixed I can patiently wait :)

**Comment by lostintangent** [comment]
@barahonajm Hmm, OK thanks for confirming that. Do you know if you're logged in with Live Share? Could you try running `Live Share: Sign Out` and then `Live Share: Sign In`, and see if that fixes things?

**Comment by barahonajm** [comment]
Thank you! @lostintangent  it works now, I was logged but restarting it worked for me.

**Comment by lostintangent** [comment]
@barahonajm Awesome! We'll try to resolve this bug for good, and please let us know if you run into any other issues.

BTW, since this is an early extension, I'd love to hear if you could share what you're planning to use it for. We need any and all feedback on how to make the experience better :)

**Comment by barahonajm** [comment]
Sure @lostintangent, I am currently using this to run a class (only 1 session so fare), the features I have seen are awesome, and of course I will provide all my feedback  after using it a couple of times (trying to don't mix specific classrrom features with spaces :) )

**Comment by lostintangent** [comment]
@barahonajm Awesome! Actually, please let us know if you have any classroom specific requests as well. Classrooms are a key scenario we'd like to enable with spaces, so I'd really appreciate any feedback you had here.

**Comment by Camo30** [comment]
Same issue here (error 401) while creating a new space. I've already tried to `Live Share: Sign Out` and `Live Share: Sign In` using the Microsoft Login and it still fails. Reloading VS Code doesn't change anything. Any thoughts?

**Comment by legomushroom** [comment]
Hey @Camo30, thanks for reporting this. `Sign out` -> `Sign in` should help. What Microsoft account do you use to sign in, it is outlook?

**Comment by Camo30** [comment]
It's an Office 365 account used for work. After login it asked for some app permissions which were permitted, but the error is still the same.

**Comment by Camo30** [comment]
@legomushroom After updating VS Code to 1.42 the 401 error message is gone but the "Join space" button seams to be dead as it does not do anything.

**Comment by andymac4182** [comment]
I have tried sign out and sign in again. Still receiving this error when signing in with a Microsoft account.

```
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

```
[2020-03-12 10:15:58.023] [renderer1] [error] Request failed with status code 401: Error: Request failed with status code 401
    at e.exports (c:\Users\andrewm\.vscode\extensions\vsls-contrib.spaces-0.1.2\out\extension.js:1:50450)
    at e.exports (c:\Users\andrewm\.vscode\extensions\vsls-contrib.spaces-0.1.2\out\extension.js:1:110355)
    at IncomingMessage.<anonymous> (c:\Users\andrewm\.vscode\extensions\vsls-contrib.spaces-0.1.2\out\extension.js:8:5340)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by wrgrant** [comment]
Just this moment I received the exact error that @andymac4182 posted.

```
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by me-tantaroth** [comment]
Hi I am connected with the **GitHub** account from **Google Chrome**, I am using this to run an **angular project** and I am getting this **error**:

`Connect to Codespace: List codespaces request failed with status 401. Correlation ID: 0401:40BC:73947:F25E8:613CCF30`

This **cannot serve** my angular project.

> **Device:** Chromebook
> **Client:** Browser (Google Chrome)
> **Login:** GitHub
> **Project:** Web App (Angular & Firebase)
