### ISSUE TITLE
Error 500 when trying to join space

### ISSUE THREAD

**Issue by edwardbrowncross** [vsls-contrib/spaces#120]
When I try to join a space, all I see is an error. A toast in VS Code shows:
```
Command 'Live Share Spaces: Join Space' resulted in an error (Request failed with status code 500)
```

And the VS Code window log shows:
```
[2020-07-29 10:09:28.545] [renderer1] [error] Request failed with status code 500: Error: Request failed with status code 500
	at e.exports (c:\Users\Edward Browncross\.vscode\extensions\vsls-contrib.spaces-0.1.2\out\extension.js:1:50450)
	at e.exports (c:\Users\Edward Browncross\.vscode\extensions\vsls-contrib.spaces-0.1.2\out\extension.js:1:110355)
	at IncomingMessage.<anonymous> (c:\Users\Edward Browncross\.vscode\extensions\vsls-contrib.spaces-0.1.2\out\extension.js:8:5340)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by edwardbrowncross** [comment]
To investigate further, I started a local instance of the service, which gave this error:

```

**Comment by legomushroom** [comment]
Hey @edwardbrowncross , pardon for the trouble, I'll investigate the issue shortly. AFAIR LiveShare requires an email on the profile to properly work, so at this point, it is not clear if that the issue on the Spaces side or not. Are you able to use LiveShare with this account?

**Comment by legomushroom** [comment]
Created the PR to fix this: https://github.com/vsls-contrib/spaces/pull/125 Please confirm that it solves your issue.

**Comment by edwardbrowncross** [comment]
Thanks for looking at this so quickly! Yes I am able to use LiveShare. My colleagues, who all have had the same experience as me, can also use it. We all have `(null)` as our email address though as this screenshot shows:
![image](https://user-images.githubusercontent.com/35063432/89179991-c83e0e00-d588-11ea-8ab9-36fd8e324162.png)

In case it helps, my LiveShare user profile data looks like this:
```
{
    "initialProvider": "github",
    "status": "accepted",
    "registrationData": {},
    "providers": {
        "github": {
            "id": "35063432",
            "profileUrl": "https://github.com/edwardbrowncross",
            "displayName": "Edward Browncross",
            "username": "edwardbrowncross",
            "initials": "EB",
            "provider": "github",
            "photos": [
                {
                    "value": "https://avatars2.githubusercontent.com/u/35063432?v=4"
                }
            ],
            "emails": []
        }
    },
    "signupTime": 1596123945571,
    "telemetryId": "1b50d591-8e7b-49cf-bdb3-31521f063035",
    "id": "acaddbe1-d891-4548-ab43-28e7f138c568",
    "workspaces": []
}
```

**Comment by legomushroom** [comment]
Thanks, AFAIR LiveShare was dependent on the emails to be present at some point and looks like that have changed recently. Unfortunately, the LS Spaces client expects the email to be present in many places and that will need to be refactored. From my smoke testing, the PR above makes LS Spaces usable, but of course, I could not do the comprehensive testing tonight. cc @lostintangent
